### PR TITLE
Add Default Class Option ;F

### LINKED ISSUE #8: Lack of default sizes
When you copy an icon from [heroicons.com](https://heroicons.com), both the SVG and the JSX versions come with `.h-6` & `.w-6` classes for medium icons and `.h-5` & `.w-5` classes for small icons.

When using TailwindCSS, this produces correct icon sizes most of the times. Well, at least from my experience it does. So when I go with the copy&paste approach, in most cases I don't have to provide extra classes or styles, it just works.

But it seems to me that with Heroicon, I will need to provide these classes manually all the time. Right now, my typical usage of Heroicon looks like this:
```erb
<%= heroicon 'chevron-right', options: { class: "h-5 w-5" } %>
```
But I'd really love to be able to use this 9 out of 10 times instead:
```erb
<%= heroicon 'chevron-right' %>
```
In other words, would be great if we have to provide options only for non-standard use cases, like custom sizes, positioning classes etc, otherwise we use the bare helper.

This could be configurable to allow overriding the defaults. For example, like this:

```ruby
Heroicon.configure do |config|
  config.variant = :solid
  config.classes = { outline: 'h-6 w-6', solid: 'h-5 w-5' }
end
```

I'd  argue that these values should come as default. I understand that not everyone is using TailwindCSS, but if you copy the icons from the official site, you are getting those classes anyway. So if this gem is about replacing the copy&paste step in your workflow while leaving everything else unchanged, then these defaults make sense.

What do you guys think?

Maybe I missed something and it is already possible achieve this?

### PR DESCRIPTION
**Pull request by bharget**
Adds a default class option to set a class name that gets applied to every icon by default. _Note: Adding a class in the view gets appended to the default when set._

Assuming the config is set like this:

```ruby
Heroicon.configure do |config|
 config.variant = :solid
 config.default_class = {solid: "h-5 w-5", outline: "h-6 w-6"}
end
```

You could do this in your view:
```erb
<%= heroicon "user" %>
```
```html
<svg class="h-5 w-5">...</svg>
```

You can also still add you own custom classes
```erb
<%= heroicon "user", options: {class: "text-red-500"} %>
```
```html
<svg class="h-5 w-5 text-red-500">...</svg>
```

_Note: setting the `default_class` configuration to a String will apply the class to every variant._

```ruby
Heroicon.configure do |config|
 config.variant = :solid
 config.default_class = "h-5 w-5"
end
```
Fixes #8

### CODE REVIEW

**Comment by mzrnsh** [comment]
I believe we need the ability to add individual default classes for outline and solid variants.

According to the [official website](https://heroicons.com), outline icons are _designed to be rendered at 24x24_ and solid icons are _designed to be rendered at 20x20_.

To make that happen, these two variants have varying width and height by default. You can see this when copying icons from the website:

### Outline icon
```svg
<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
...
</svg>
```


### Solid icon
```svg
<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
...
</svg>
```

Is there a reason why we would prefer to have a single default class and deviate from the underlying library's approach?

**Comment by bharget** [comment]
> Is there a reason why we would prefer to have a single default class and deviate from the underlying library's approach?

Not at all, and thank you for pointing out that difference in the docs! I'll update this PR.

**Comment by mzrnsh** [comment]
Great!

I believe the README needs a couple updates in the context of this PR. Obviously, it won't hurt if this new config option is described. In addition, we need a note regarding PurgeCSS or alternatives, for whoever is using them:

We should probably recommend adding `config/initializers/heroicon.rb` to the list of purged paths. I know I would not figure out this part myself when installing a new gem and get ridiculous icons in production.

**Comment by bharget** [comment]
Hey @mzrnsh, I just pushed up some changes to this branch, including a README update. Let me know if you had any additional thoughts on what you were looking for here!

> I will gladly assist with this.

I really appreciate that! You are of course more than welcome to open a PR if there is something more that you would like to add!

**Comment by mzrnsh** [comment]
@bharget Looking good!

I do have one more question: what should happen when you have both the `default_class` configured and provide `class` option from the view?

Maybe I should have thought about this earlier, but I only noticed this when testing your branch.

Example:
```erb
<%= heroicon 'academic-cap', variant: :outline, options: { class: 'text-red-500 w-4 h-4' } %>
```

This gives me the following HTML:
```html
<svg ... class="h-6 w-6 text-red-500 w-4 h-4">
  ...
</svg>
```

I now have both the default classes and the overriding classes present in the class attribute. Sometimes, like in my case, these classes will conflict. It's also possible that in some scenarios these two set of classes won't conflict and instead complement each other. For example, config classes affect sizing and view classes affect colors. But when they do conflict, you will have no way to force the overriding classes to prevail which kind of defeats the purpose of this whole feature.

So I guess, I have an answer for my own question: we should probably replace config classes with view classes when the latter is provided.

So instead of `class="h-6 w-6 text-red-500 w-4 h-4"` I should have ended up with `class="text-red-500 w-4 h-4"`.

What do you think?

**Comment by bharget** [comment]
> I do have one more question: what should happen when you have both the default_class configured and provide class option from the view?

I went back and forth on that — What do you think about adding an option to disable setting a default class? @mzrnsh 

```erb
<%= heroicon "user", options: { class: "conflicting styles", disable_default_class: true } %>
```

I feel like the conflicting styles is going to be way less common than someone trying to add an additional class to the icon (such as `text-red-500`).

A total replacement would mean that someone would need to remember to add the default classes if they add any additional classes.

**Comment by mzrnsh** [comment]
> What do you think about adding an option to disable setting a default class?

> I feel like the conflicting styles is going to be way less common than someone trying to add an additional class

Agree 👍

**Pull request merged**
