### PR TITLE
heroicons 2.0.13

### PR DESCRIPTION
**Pull request by simmerz**
Updated for 2.0.11 which has just been released.

### CODE REVIEW

**Comment by simmerz** [comment]
@henrikbjorn @bharget I'll update this PR to 2.0.13 which was released a few days ago rather than merge this in as is.

**Comment by simmerz** [comment]
@bharget can this be merged now? Fully up to date with upstream.

**Review by tarellel — APPROVED** [review]

**Comment by bharget** [comment]
Sorry for the delay 😅

**Comment by henrikbjorn** [comment]
@bharget Do you mind cutting a new release

**Pull request merged**
